language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t saurabh333/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true saurabh333/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-313447773450'
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: 
    secure: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRET_KEY'

